### ISSUE TITLE
Импорт выдает ошибку: BulkSave, deadlock

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#44]
При импорте файла 
https://drive.google.com/file/d/1qbrffZHo0xja4yhF6hAF11khnZiASbNn/view?usp=sharing
"Дагестан 2016 Мятлев v2 с нумерацией.xlsx"
сервер выдает ошибку
![image](https://user-images.githubusercontent.com/36114863/45121294-62149a80-b169-11e8-834a-d9e7014d0c25.png)
(хотя визуально проблем в базе нет, файл аналогичен "Test from President Shpilkin 2018 UTF-8 ‎10.04.‎2018 v3 few columns few rows", который проблем не вызывает (там же)

**Comment by ybinzu** [comment]
Ошибка при импорте:

[error_44.log](https://github.com/GolosMovement/StatElectGenerator/files/2356023/error_44.log)

**Comment by ybinzu** [comment]
`System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 51) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.`

**Comment by ybinzu** [comment]
```
   at ElectionStatistics.Core.Import.DbSerializer.BulkSave() in /StatElectGenerator/ElectionStatistics.Core/Import/DbSerializer.cs:line 112
   at ElectionStatistics.Core.Import.DbSerializer.CreateLineNumber(LineNumber lineNumber) in /StatElectGenerator/ElectionStatistics.Core/Import/DbSerializer.cs:line 92
   at ElectionStatistics.Core.Import.Service.CreateLines(Int32 line, Protocol protocol, List`1 mappings, IExcelDataReader reader) in /StatElectGenerator/ElectionStatistics.Core/Import/Service.cs:line 357
   at ElectionStatistics.Core.Import.Service.ImportXlsx(String xlsxFile, Mapping mapping, ProtocolSet protocolSet, List`1 allMappings) in /StatElectGenerator/ElectionStatistics.Core/Import/Service.cs:line 118
   at ElectionStatistics.Core.Import.Service.Execute(String xlsxFile, ProtocolSet protocolSet, Mapping mapping, List`1 mappingLines) in /StatElectGenerator/ElectionStatistics.Core/Import/Service.cs:line 30
   at ElectionStatistics.WebSite.ImportController.Create(IFormFile file, String mappingTable, String protocolSet, Int32 startLine) in /StatElectGenerator/ElectionStatistics.WebSite/Import/ImportController.cs:line 83
   at lambda_method(Closure , Object , Object[] )
```
