### ISSUE TITLE
LDA зависает 

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#46]
Обрабатывая данные импорта ProtocolSet "Тест 3 Дагестан" (импорт с нумерацией)
LDA зависает. 
(видимых проблем в импортированных данных нет) 
Зависание происходит на сколь угодно малой выборке (даже на уровне выбранного ТИК)

**Comment by ybinzu** [comment]
Задеплоил.

**Comment by ybinzu** [comment]
Проверил на дагестанской базе, падает с ошибкой:

```fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.ArgumentException: lineNumbers should not be empty
   at ElectionStatistics.Core.Methods.LastDigitAnalyzer.GetData(List`1 lineNumbers, Nullable`1 minValue) in /Users/artembaikuzin/dotnet/StatElectGenerator/ElectionStatistics.Core/Methods/LastDigitAnalyzer.cs:line 30
   at ElectionStatistics.WebSite.ChartsController.GetDataForLastDigitAnalyzer(String parametersString) in /Users/artembaikuzin/dotnet/StatElectGenerator/ElectionStatistics.WebSite/Chart/ChartsController.cs:line 338
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)```

Параметры (импортировал БД локально, не на проде):
![dag](https://user-images.githubusercontent.com/1109847/45160590-908a8800-b1f2-11e8-85f4-f2eb1eb9dd3a.png)

**Comment by BlackWrangler** [comment]
У меня работает штатно. Считает как при ручном подсчёте 
Авто:
![image](https://user-images.githubusercontent.com/36114863/45161561-da746d80-b1f4-11e8-9916-91631fa3af12.png)
Ручное: 
![image](https://user-images.githubusercontent.com/36114863/45161632-faa42c80-b1f4-11e8-8520-f926a06d184c.png)
цифры совпадают
![image](https://user-images.githubusercontent.com/36114863/45161697-1dcedc00-b1f5-11e8-8073-9ca1ff4e06aa.png)

**Comment by ybinzu** [comment]
Проблема только на пустых выборках, исправляем.

**Comment by ybinzu** [comment]
Задеплоил фикс a62362a
