### ISSUE TITLE
Server error при импорте

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#57]
При импорте https://drive.google.com/file/d/1SR7p8-W4KrhNkH6EKV4R6CUWEUdwimkI/view?usp=sharing
С маппингом "Дума 2011 тест неполн. перем."
Появляется сообщение об ошибке 
![image](https://user-images.githubusercontent.com/36114863/45258151-9e3f3980-b3bb-11e8-8d69-24a99cb06428.png)
База заполняется медленно. В обработанной части проблем не вижу.

**Comment by ybinzu** [comment]
```Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: Unknown error: 258
   --- End of inner exception stac
[bulk-insertions-error.log](https://github.com/GolosMovement/StatElectGenerator/files/2364504/bulk-insertions-error.log)
k trace ---
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at ElectionStatistics.Core.Import.DbSerializer.BulkSave() in StatElectGenerator/ElectionStatistics.Core/Import/DbSerializer.cs:line 112
   at ElectionStatistics.Core.Import.DbSerializer.CreateLineNumber(LineNumber lineNumber) in StatElectGenerator/ElectionStatistics.Core/Import/DbSerializer.cs:line 92
   at ElectionStatistics.Core.Import.Service.CreateLines(Int32 line, Protocol protocol, List`1 mappings, IExcelDataReader reader) in StatElectGenerator/ElectionStatistics.Core/Import/Service.cs:line 357
   at ElectionStatistics.Core.Import.Service.ImportXlsx(String xlsxFile, Mapping mapping, ProtocolSet protocolSet, List`1 allMappings) in StatElectGenerator/ElectionStatistics.Core/Import/Service.cs:line 118
   at ElectionStatistics.Core.Import.Service.Execute(String xlsxFile, ProtocolSet protocolSet, Mapping mapping, List`1 mappingLines) in StatElectGenerator/ElectionStatistics.Core/Import/Service.cs:line 30
   at ElectionStatistics.WebSite.ImportController.Create(IFormFile file, String mappingTable, String protocolSet, Int32 startLine) in StatElectGenerator/ElectionStatistics.WebSite/Import/ImportController.cs:line 84
   at lambda_method(Closure , Object , Object[] )
```

**Comment by ybinzu** [comment]
Bulk insertion падает по timeout

**Comment by ybinzu** [comment]
Пробую прикрутить https://github.com/borisdj/EFCore.BulkExtensions

**Comment by ybinzu** [comment]
Пробую вариант с чистым `System.Data.SqlClient.SqlConnection`. `BulkExtensions` пока отложил из-за сложной реализации, т.к. данные сначала нужно будет накопить в памяти с сохранением иерархии (Tree или OrderedDictionary), потом уже вызывать создания родителей для определения Id, затем выдать всем подчиненным записям Id и снова вызывать создание записей и т.д. Надеюсь на то, что транзакции + `SqlConnection` будут также быстры как `BulkExtensions`. Сделаю тест на 500к записей перед реализацией непосредственного `DbSerializer`.

**Comment by ybinzu** [comment]
На 500к записей `SqlConnection` работает 3:19 секунд. По-моему это все равно медленно, если учесть, что в результатах выборов может быть 160-200к строк и 32 колонки (6.4 млн вставок, будет работать примерно 45 минут).

```csharp
using (SqlConnection connection = new SqlConnection(Configuration.GetConnectionString("ElectionStatisticsDatabase")))
{
    connection.Open();

    var transaction = connection.BeginTransaction();

    using (SqlCommand cmd = new SqlCommand("INSERT INTO Mappings(Name) output INSERTED.ID VALUES(@name)", connection))
    {
        for (int i = 0; i < 50000; i++)
        {
            cmd.Transaction = transaction;
            cmd.Parameters.Clear();
            cmd.Parameters.AddWithValue("@name", string.Format("{0}", i));

            int id = (int) cmd.ExecuteScalar();

            if (i % 4000 == 0)
            {
                transaction.Commit();
                transaction = connection.BeginTransaction();
            }
        }
    }

    transaction.Commit();
    connection.Close();
}
```

**Comment by ybinzu** [comment]
При этом, тест с `BulkExtensions` провалился на 500к записях - падает с ошибкой таймаута (`System.Data.SqlClient.SqlException: Timeout expired.`), хотя используется локальная БД (не azure).

Но при этом, `BulkExtensions` и `SqlConnection ` работают примерно с одинаковой скоростью на 50к записей - 20 секунд. Возможно, даже если решить проблему с timeout у `BulkExtensions` то скорости это не добавит (будут те же 3 минуты с копейками).

```csharp
var optionsBuilder = new DbContextOptionsBuilder<ModelContext>();
var modelContext = new ModelContext(optionsBuilder.UseSqlServer(
    Configuration.GetConnectionString(
        "ElectionStatisticsDatabase")).Options);

var mappingList = new List<Mapping>();

for (int i = 0; i < 500000; i++)
{
    var mapping = new Mapping();
    mapping.Name = string.Format("{0}", i);
    mapping.DataLineNumber = i;
    mappingList.Add(mapping);
}

modelContext.BulkInsert(mappingList,
    new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true, BatchSize = 4000 });
```

<details>
<summary>System.Data.SqlClient.SqlException</summary>

```
Application startup exception: System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): Unknown error: 258
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at ElectionStatistics.WebSite.Startup.ConfigureServices(IServiceCollection services) in /dotnet/StatElectGenerator/ElectionStatistics.WebSite/Startup.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
ClientConnectionId:59cd08f9-9da0-4000-8250-570cd98e0795
Error Number:-2,State:0,Class:11

Unhandled Exception: System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: Unknown error: 258
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at ElectionStatistics.WebSite.Startup.ConfigureServices(IServiceCollection services) in /dotnet/StatElectGenerator/ElectionStatistics.WebSite/Startup.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at ElectionStatistics.WebSite.Program.BuildWebHost(String[] args) in /dotnet/StatElectGenerator/ElectionStatistics.WebSite/Program.cs:line 21
   at ElectionStatistics.WebSite.Program.Main(String[] args) in /dotnet/StatElectGenerator/ElectionStatistics.WebSite/Program.cs:line 17
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): Unknown error: 258
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNon
```
</details>

**Comment by ybinzu** [comment]
Вставка 500k записей на обычном EF сравнима по скорости с чистым `SqlConnection`: 3 минуты, 29 секунд (условия те же):

```csharp
var optionsBuilder = new DbContextOptionsBuilder<ModelContext>();
optionsBuilder.UseSqlServer(connectionString)
    .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

DbContext context = new ModelContext(optionsBuilder.Options);

for (int i = 0; i < 500000; i++)
{
    var mapping = new Mapping();
    mapping.Name = string.Format("{0}", i);
    mapping.DataLineNumber = i;

    context.Set<Mapping>().Add(mapping);

    if (i % 4000 == 0)
    {
        context.SaveChanges();
    }
}
context.SaveChanges();
```

**Comment by ybinzu** [comment]
Такой же тест на ruby дает чуть больше 2 минут на sql и более 13 минут на `ActiveRecord`:

```ruby
class BulkInsertions
  # Running time: 806.9907
  def self.test_active_record
    measure do
      count = 0

      (0...125).each do
        ActiveRecord::Base.transaction do
          (0...4000).each do
            FavouriteRoute.create(name: count.to_s, usage: count)
            count += 1
          end
        end
      end
    end
  end


  # Running time: 129.930718
  def self.test_plain_sql
    measure do
      count = 0

      (0...125).each do
        ActiveRecord::Base.transaction do
          (0...4000).each do
            result = ActiveRecord::Base.connection.execute(
              "INSERT INTO favourite_routes(usage, name, created_at, updated_at) " \
              "VALUES (#{count}, #{count}, current_timestamp, current_timestamp) RETURNING id;")
            count += 1
          end
        end
      end
    end
  end

  def self.measure(&block)
    start = Time.now
    block.call
    stop = Time.now

    puts("Running time: #{stop - start}")
  end
end
```

**Comment by ybinzu** [comment]
Смысла тестировать дальше нет, сделаем обработку в фоновом режиме и вывод прогресса через сокеты:

#63
