### ISSUE TITLE
Запускать обработку импорта отдельным фоновым процессом

### ISSUE THREAD

**Issue by ybinzu** [GolosMovement/StatElectGenerator#63]
Отдавать прогресс через websockets.

Интерфейс:
 - [ ] #58

**Comment by ybinzu** [comment]
Если два раза подрят отдать что-то на импорт, то появляется ошибка:

```
fail: ElectionStatistics.Core.Import.QueueService[0]
      Error occured in a background process
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'ModelContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at ElectionStatistics.Core.Import.DbSerializer..ctor(DbContext context) in dotnet/StatElectGenerator/ElectionStatistics.Core/Import/DbSerializer.cs:line 16
   at ElectionStatistics.WebSite.ImportController.<>c__DisplayClass6_1.<Create>b__1() in dotnet/StatElectGenerator/ElectionStatistics.WebSite/Import/ImportController.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at ElectionStatistics.WebSite.ImportController.<>c__DisplayClass6_0.<<Create>b__0>d.MoveNext() in dotnet/StatElectGenerator/ElectionStatistics.WebSite/Import/ImportController.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at ElectionStatistics.Core.Import.QueueService.ExecuteAsync(CancellationToken cancellationToken) in dotnet/StatElectGenerator/ElectionStatistics.Core/Import/QueueService.cs:line 46
```

**Comment by ybinzu** [comment]
После старта приложения запускается `IHostedService`: `QueueService`, который ждет появления в очереди задач на импорт. Задачи на импорт передаются через `Singleton`: `BackgroundQueue`. Прогресс передается в БД каждые 15 секунд при помощи `DbProgressNotifier: IProgressNotifier`.

**Comment by ybinzu** [comment]
Текущий прогресс возвращается в `ProtocolSet` в поля:

```csharp
        public DateTime? ImportStartedAt { get; set; }
        public DateTime? ImportFinishedAt { get; set; }
        public int ImportTotalLines { get; set; }
        public int ImportCurrentLine { get; set; }
        public bool ImportSuccess { get; set; }
        public int ImportErrorCount { get; set; }
```

`ImportSuccess` - индикатор того, что не было непредвиденных exceptions. `ImportErrorCount` - количество ошибочных строк собранных в файл ошибок (`IErrorLogger`).

`ImportStartedAt` - дата/время начала импорта, `ImportFinishedAt` - дата/время завершения.
