### ISSUE TITLE
Ошибки при Импорте Франция Президент 2017 

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#85]
1. Делался импорт файла 
Франция Президент 2017 II тур (https://drive.google.com/file/d/18uiQnJFZJVA1eY96pKYeJz7BQDy5DI1F/view?usp=sharing)
Маппинг: "Франция Президент 2017 II тур Шпилькин"
Контент-менеджер ошибался. Система сигнализировала. Ошибки исправлялись. В итоге после исправления всех ошибок, импорт НЕ прошел, но сообщений об ошибках нет. 
Задача: понять что происходит. Добавить сообщение о подобных в error log. 

Просьба сделать до разделения на Stage и Product , чтобы лишний раз не сливать. Мы будем уже тестировать Product на пользователях.

**Comment by ybinzu** [comment]
```
fail: ElectionStatistics.Core.Import.QueueService[0]
      Error occured in a background process
System.InvalidOperationException: Column 'Value' does not allow DBNull.Value.
   at System.Data.SqlClient.SqlBulkCopy.ConvertValue(Object value, _SqlMetaData metadata, Boolean isNull, Boolean& isSqlType, Boolean& coercedToDataFeed)
   at System.Data.SqlClient.SqlBulkCopy.ReadWriteColumnValueAsync(Int32 col)
   at System.Data.SqlClient.SqlBulkCopy.CopyColumnsAsync(Int32 col, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyRowsAsync(Int32 rowsSoFar, Int32 totalRows, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(DbDataReader reader)
   at EFCore.BulkExtensions.SqlBulkOperation.Insert[T](DbContext context, IList`1 entities, TableInfo tableInfo, Action`1 progress)
   at ElectionStatistics.Core.Import.DbSerializer.AfterImport() in StatElectGenerator/ElectionStatistics.Core/Import/DbSerializer.cs:line 75
   at ElectionStatistics.Core.Import.Service.ImportXlsx(String xlsxFile, Mapping mapping, ProtocolSet protocolSet, List`1 allMappings) in StatElectGenerator/ElectionStatistics.Core/Import/Service.cs:line 237
   at ElectionStatistics.Core.Import.Service.Execute(ISerializer serializer, IProgressNotifier notifier) in StatElectGenerator/ElectionStatistics.Core/Import/Service.cs:line 93
   at ElectionStatistics.WebSite.ImportController.<>c__DisplayClass7_1.<Create>b__2() in StatElectGenerator/ElectionStatistics.WebSite/Import/ImportController.cs:line 128
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at ElectionStatistics.WebSite.ImportController.<>c__DisplayClass7_0.<<Create>b__0>d.MoveNext() in StatElectGenerator/ElectionStatistics.WebSite/Import/ImportController.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at ElectionStatistics.Core.Import.QueueService.ExecuteAsync(CancellationToken cancellationToken) in StatElectGenerator/ElectionStatistics.Core/Import/QueueService.cs:line 43
```

**Comment by ybinzu** [comment]
Поправил ошибку в https://github.com/GolosMovement/StatElectGenerator/commit/a4f6609faefa91b344ee309c858db0377c039ad8
(В коммите неверно указал номер задачи)

1. Не создаю `LineString` и не считаю это ошибкой, если во входном файле xlsx значение поля null.
1. Добавил запись в лог в случае непредвиденной ошибки (Exception).
1. Явно присваиваю `LineNumber.Value = 0`, если значение поля в xlsx null. Раньше это делал EF приводя null к 0 автоматически.

Франция импортировалась успешно как FRA6:
<img width="1070" alt="screenshot 2018-11-07 at 13 12 05" src="https://user-images.githubusercontent.com/1109847/48125508-ec739a80-e28f-11e8-87aa-e6c554b1438a.png">

Импортировал при помощи маппинга `france_fixed`, поправил в нем только `С какой строки начинаются данные: 14`.

Остальные импорты по франции неуспешны `FRA*`.

**Comment by BlackWrangler** [comment]
1. По lineString не вижу проблем. Когда мы восстанавливаем данные - восстанавливаются пустые клеточки, что соответствует исходным данным. 
2. Это хорошо, знать что ошибка произошла (но это было видно и по красной полосе). Хотя бы подсказка контент-менеджеру. 
3. В отличие от lineString, тут есть логическая ошибка. Я её опишу в отдельном issue. В принципе: числовые показатели результатов голосования - количества реальных физических объектов. Если стоит 0 - значит объектов было 0. Если же стоит "", значит тут что-то другое. В традициях ЦИК РФ так помечать отмененные выборы (я говорил Артёму и писал об этом https://docs.google.com/document/d/10gNc5Cdme6wKCwx4PqKmWaqQ64RuYqxQQQg1WkpmLeE/edit?usp=sharing (в конце страницы) )
