### ISSUE TITLE
Сбой импорта 

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#91]
Файл https://github.com/GolosMovement/StatElectGenerator/blob/develop/Source%20Data/%D0%9F%D1%80%D0%B5%D0%B7%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%202012%20%D0%A8%D0%BF%D0%B8%D0%BB%D1%8C%D0%BA%D0%B8%D0%BD.xlsx

При импорте (mapping РФ Президент 2012 Шпилькин, Product) вызывает необычный сбой
```
95417:1 (A): System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ExcelDataReader.ExcelDataReader`2.GetValue(Int32 i)
   at ExcelDataReader.ExcelDataReader`2.GetFieldType(Int32 i)
   at ElectionStatistics.Core.Import.Service.UpdateHierarchy(Int32 line, ProtocolSet protocolSet, Dictionary`2 createdProtocols, List`1 hierarchy, IExcelDataReader reader) in D:\home\site\repository\ElectionStatistics.Core\Import\Service.cs:line 374
   at ElectionStatistics.Core.Import.Service.ImportXlsx(String xlsxFile, Mapping mapping, ProtocolSet protocolSet, List`1 allMappings) in D:\home\site\repository\ElectionStatistics.Core\Import\Service.cs:line 211
```

Ячейка 95417:1 (A) выглядит пустой с точки зрения Excel.

**Comment by BlackWrangler** [comment]
Какая интересная логика )) 
Пока встречались данные для импорта только на одном листе.
