### ISSUE TITLE
Пресеты: System.ArgumentOutOfRangeException: Length cannot be less than zero

### ISSUE THREAD

**Issue by ybinzu** [GolosMovement/StatElectGenerator#95]
Расчет пресетов для `Губернатор Чукотки 2018` вызывает:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ElectionStatistics.Core.Preset.Calculator.ExecuteSingle(Protocol protocol) in StatElectGenerator/ElectionStatistics.Core/Preset/Calculator.cs:line 61
   at ElectionStatistics.Core.Preset.Calculator.<Execute>b__5_6(Protocol protocol) in StatElectGenerator/ElectionStatistics.Core/Preset/Calculator.cs:line 44
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ElectionStatistics.Core.Preset.Calculator.Execute() in StatElectGenerator/ElectionStatistics.Core/Preset/Calculator.cs:line 43
   at ElectionStatistics.WebSite.PresetManagerController.<>c__DisplayClass7_1.<RecalcPresets>b__3(Preset preset) in StatElectGenerator/ElectionStatistics.WebSite/PresetManager/PresetManagerController.cs:line 151
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ElectionStatistics.WebSite.PresetManagerController.RecalcPresets(Int32 protocolSetId) in StatElectGenerator/ElectionStatistics.WebSite/PresetManager/PresetManagerController.cs:line 148
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at ElectionStatistics.Core.Preset.Calculator.<>c__DisplayClass7_0.<GetMatchedLineNumbers>b__0(Int32 lineDescrId) in StatElectGenerator/ElectionStatistics.Core/Preset/Calculator.cs:line 76
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ElectionStatistics.Core.Preset.Calculator.GetMatchedLineNumbers(Protocol protocol) in StatElectGenerator/ElectionStatistics.Core/Preset/Calculator.cs:line 75
   at ElectionStatistics.Core.Preset.Calculator.ExecuteSingle(Protocol protocol) in StatElectGenerator/ElectionStatistics.Core/Preset/Calculator.cs:line 55
   at ElectionStatistics.Core.Preset.Calculator.<Execute>b__5_6(Protocol protocol) in StatElectGenerator/ElectionStatistics.Core/Preset/Calculator.cs:line 44
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ElectionStatistics.Core.Preset.Calculator.Execute() in StatElectGenerator/ElectionStatistics.Core/Preset/Calculator.cs:line 43
   at ElectionStatistics.WebSite.PresetManagerController.<>c__DisplayClass7_1.<RecalcPresets>b__3(Preset preset) in StatElectGenerator/ElectionStatistics.WebSite/PresetManager/PresetManagerController.cs:line 151
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ElectionStatistics.WebSite.PresetManagerController.RecalcPresets(Int32 protocolSetId) in StatElectGenerator/ElectionStatistics.WebSite/PresetManager/PresetManagerController.cs:line 148
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by ybinzu** [comment]
В этой же задаче поменяем формат самих формул пресетов, т.к. ошибка связана с формулой вида (повторяющиеся ИД 196):

`196 / (196 + 197)`

Теперь нужно будет задавать ИД в квадратных скобках, чтобы отделять числа от ИД `LineDescriptions`:

`[196] / ([196] + [197]) * 100.0`

**Comment by rgarifullin** [comment]
**Staging** обновлен.
Preset'ы для выборов "Губернатор Чукотки 2018" приведены в соответствие с новым форматом и успешно предрасчитаны (около 6 секунд). GBDV строится.
