### ISSUE TITLE
Пресеты: System.Data.SyntaxErrorException: Syntax error: Missing operand after '+' operator

### ISSUE THREAD

**Issue by ybinzu** [GolosMovement/StatElectGenerator#97]
Выявляется если пытаться рассчитывать пресеты staging `QA #6-2`:
```
System.Data.SyntaxErrorException: Syntax error: Missing operand after '+' operator.
   at System.Data.ExpressionParser.Parse()
   at System.Data.DataExpression..ctor(DataTable table, String expression, Type type)
   at System.Data.DataTable.Compute(String expression, String filter)
   at ElectionStatistics.Core.Preset.Calculator.ExecuteSingle(Protocol protocol) in /StatElectGenerator/ElectionStatistics.Core/Preset/Calculator.cs:line 62
   at ElectionStatistics.Core.Preset.Calculator.<Execute>b__5_6(Protocol protocol) in /StatElectGenerator/ElectionStatistics.Core/Preset/Calculator.cs:line 44
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ElectionStatistics.Core.Preset.Calculator.Execute() in /StatElectGenerator/ElectionStatistics.Core/Preset/Calculator.cs:line 43
   at ElectionStatistics.WebSite.PresetManagerController.<>c__DisplayClass7_1.<RecalcPresets>b__3(Preset preset) in /StatElectGenerator/ElectionStatistics.WebSite/PresetManager/PresetManagerController.cs:line 151
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ElectionStatistics.WebSite.PresetManagerController.RecalcPresets(Int32 protocolSetId) in /StatElectGenerator/ElectionStatistics.WebSite/PresetManager/PresetManagerController.cs:line 148
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by ybinzu** [comment]
Пресеты заполнены правильно:

```
"Явка % тест"
([701]+[702]+[703])/[699]

"ЛДПР % тест"
[718]/([707]+[708])
```

**Comment by ybinzu** [comment]
В калькулятор попадали `null` значения из `LineNumbers`. Переделал работу с такими случаями, а также когда формула не имеет решения (деление на 0, например) - будет возвращать `null`. Поправил GBDV - не запрашивает `null` значения из `LineCalculatedValue`.

Обновил staging.
